apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-api-deployment
  labels:
    service: shortener
    # kind: api
spec:
  replicas: 5
  selector:
    matchLabels:
      service: shortener
      # kind: api
  template:
    metadata:
      labels:
        service: shortener
        # kind: api
    spec:
      containers:
        - name: shortener-api
          image: kuberneteslearning/shortener.api:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: API__CODE__URL
              value: http://code:80
            - name: DATABASE__CONNECTIONSTRING
              value: Host=shortener-db-loadbalancer;Database=ShortenUrl;Username=postgres;Password=01031990Pc
            - name: MESSAGING__HOST
              value: messaging-management-service
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              memory: "1024Mi"
              cpu: "750m"
---
kind: Service
apiVersion: v1
metadata:
  name:  shortner-api-service
  labels:
    service: shortener
    # kind: api
spec:
  selector:
    service: shortener
    # kind: api
  type:  LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 80
    nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  # The required headless service for StatefulSets
  name: shortner-api
  labels:
    service: shortener
    # kind: api
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    service: shortener
    kind: api